# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"core_helper": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://benjaminDev.github.io/new_wave/"

git_url = "https://github.com/benjaminDev/new_wave/tree/master/"

def custom_doc_links(name): return None
